CREATE CONSTRAINT drug_pk IF NOT EXISTS
FOR (d:Drug) REQUIRE d.rxnorm_id IS UNIQUE;

CREATE CONSTRAINT gene_pk IF NOT EXISTS
FOR (g:Gene) REQUIRE g.hgnc_id IS UNIQUE;

CREATE CONSTRAINT rna_pk IF NOT EXISTS
FOR (r:RNA) REQUIRE r.mirbase_id IS UNIQUE;

CREATE INDEX paper_pmid IF NOT EXISTS
FOR (p:Paper) ON (p.pmid);